/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiAdvisorRouteImport } from './routes/api/advisor'
import { Route as ApiPolishRouteImport } from './routes/api/polish'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleAdvisorRouteImport } from './routes/console/advisor'
import { Route as ConsoleSettingsRouteImport } from './routes/console/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiJdIngestRouteImport } from './routes/api/jd/ingest'
import { Route as ConsoleCompaniesIndexRouteImport } from './routes/console/companies/index'
import { Route as ConsoleCompaniesCompanyIdRouteImport } from './routes/console/companies/$companyId'
import { Route as ConsoleCompaniesNewRouteImport } from './routes/console/companies/new'
import { Route as ConsoleLibraryIndexRouteImport } from './routes/console/library/index'
import { Route as ConsoleResumesIndexRouteImport } from './routes/console/resumes/index'
import { Route as ConsoleResumesResumeIdRouteImport } from './routes/console/resumes/$resumeId'
import { Route as ConsoleResumesNewRouteImport } from './routes/console/resumes/new'
import { Route as ConsoleResumesResumeIdPolishRouteImport } from './routes/console/resumes/$resumeId.polish'
import { Route as ConsoleResumesResumeIdTargetsRouteImport } from './routes/console/resumes/$resumeId.targets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishRoute = ApiPolishRouteImport.update({
  id: '/api/polish',
  path: '/api/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAdvisorRoute = ConsoleAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJdIngestRoute = ApiJdIngestRouteImport.update({
  id: '/api/jd/ingest',
  path: '/api/jd/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleCompaniesIndexRoute = ConsoleCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCompaniesCompanyIdRoute =
  ConsoleCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleCompaniesNewRoute = ConsoleCompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleLibraryIndexRoute = ConsoleLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleResumesIndexRoute = ConsoleResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleResumesResumeIdRoute = ConsoleResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleResumesNewRoute = ConsoleResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleResumesResumeIdPolishRoute =
  ConsoleResumesResumeIdPolishRouteImport.update({
    id: '/polish',
    path: '/polish',
    getParentRoute: () => ConsoleResumesResumeIdRoute,
  } as any)
const ConsoleResumesResumeIdTargetsRoute =
  ConsoleResumesResumeIdTargetsRouteImport.update({
    id: '/targets',
    path: '/targets',
    getParentRoute: () => ConsoleResumesResumeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/polish': typeof ApiPolishRoute
  '/console/advisor': typeof ConsoleAdvisorRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jd/ingest': typeof ApiJdIngestRoute
  '/console/companies/$companyId': typeof ConsoleCompaniesCompanyIdRoute
  '/console/companies/new': typeof ConsoleCompaniesNewRoute
  '/console/resumes/$resumeId': typeof ConsoleResumesResumeIdRouteWithChildren
  '/console/resumes/new': typeof ConsoleResumesNewRoute
  '/console/companies/': typeof ConsoleCompaniesIndexRoute
  '/console/library/': typeof ConsoleLibraryIndexRoute
  '/console/resumes/': typeof ConsoleResumesIndexRoute
  '/console/resumes/$resumeId/polish': typeof ConsoleResumesResumeIdPolishRoute
  '/console/resumes/$resumeId/targets': typeof ConsoleResumesResumeIdTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/polish': typeof ApiPolishRoute
  '/console/advisor': typeof ConsoleAdvisorRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jd/ingest': typeof ApiJdIngestRoute
  '/console/companies/$companyId': typeof ConsoleCompaniesCompanyIdRoute
  '/console/companies/new': typeof ConsoleCompaniesNewRoute
  '/console/resumes/$resumeId': typeof ConsoleResumesResumeIdRouteWithChildren
  '/console/resumes/new': typeof ConsoleResumesNewRoute
  '/console/companies': typeof ConsoleCompaniesIndexRoute
  '/console/library': typeof ConsoleLibraryIndexRoute
  '/console/resumes': typeof ConsoleResumesIndexRoute
  '/console/resumes/$resumeId/polish': typeof ConsoleResumesResumeIdPolishRoute
  '/console/resumes/$resumeId/targets': typeof ConsoleResumesResumeIdTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/polish': typeof ApiPolishRoute
  '/console/advisor': typeof ConsoleAdvisorRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jd/ingest': typeof ApiJdIngestRoute
  '/console/companies/$companyId': typeof ConsoleCompaniesCompanyIdRoute
  '/console/companies/new': typeof ConsoleCompaniesNewRoute
  '/console/resumes/$resumeId': typeof ConsoleResumesResumeIdRouteWithChildren
  '/console/resumes/new': typeof ConsoleResumesNewRoute
  '/console/companies/': typeof ConsoleCompaniesIndexRoute
  '/console/library/': typeof ConsoleLibraryIndexRoute
  '/console/resumes/': typeof ConsoleResumesIndexRoute
  '/console/resumes/$resumeId/polish': typeof ConsoleResumesResumeIdPolishRoute
  '/console/resumes/$resumeId/targets': typeof ConsoleResumesResumeIdTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/about'
    | '/mcp'
    | '/api/advisor'
    | '/api/polish'
    | '/console/advisor'
    | '/console/settings'
    | '/console/'
    | '/api/auth/$'
    | '/api/jd/ingest'
    | '/console/companies/$companyId'
    | '/console/companies/new'
    | '/console/resumes/$resumeId'
    | '/console/resumes/new'
    | '/console/companies/'
    | '/console/library/'
    | '/console/resumes/'
    | '/console/resumes/$resumeId/polish'
    | '/console/resumes/$resumeId/targets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/advisor'
    | '/api/polish'
    | '/console/advisor'
    | '/console/settings'
    | '/console'
    | '/api/auth/$'
    | '/api/jd/ingest'
    | '/console/companies/$companyId'
    | '/console/companies/new'
    | '/console/resumes/$resumeId'
    | '/console/resumes/new'
    | '/console/companies'
    | '/console/library'
    | '/console/resumes'
    | '/console/resumes/$resumeId/polish'
    | '/console/resumes/$resumeId/targets'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/about'
    | '/mcp'
    | '/api/advisor'
    | '/api/polish'
    | '/console/advisor'
    | '/console/settings'
    | '/console/'
    | '/api/auth/$'
    | '/api/jd/ingest'
    | '/console/companies/$companyId'
    | '/console/companies/new'
    | '/console/resumes/$resumeId'
    | '/console/resumes/new'
    | '/console/companies/'
    | '/console/library/'
    | '/console/resumes/'
    | '/console/resumes/$resumeId/polish'
    | '/console/resumes/$resumeId/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  ApiAdvisorRoute: typeof ApiAdvisorRoute
  ApiPolishRoute: typeof ApiPolishRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJdIngestRoute: typeof ApiJdIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish': {
      id: '/api/polish'
      path: '/api/polish'
      fullPath: '/api/polish'
      preLoaderRoute: typeof ApiPolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/advisor': {
      id: '/console/advisor'
      path: '/advisor'
      fullPath: '/console/advisor'
      preLoaderRoute: typeof ConsoleAdvisorRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jd/ingest': {
      id: '/api/jd/ingest'
      path: '/api/jd/ingest'
      fullPath: '/api/jd/ingest'
      preLoaderRoute: typeof ApiJdIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/companies/': {
      id: '/console/companies/'
      path: '/companies'
      fullPath: '/console/companies/'
      preLoaderRoute: typeof ConsoleCompaniesIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/companies/$companyId': {
      id: '/console/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/console/companies/$companyId'
      preLoaderRoute: typeof ConsoleCompaniesCompanyIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/companies/new': {
      id: '/console/companies/new'
      path: '/companies/new'
      fullPath: '/console/companies/new'
      preLoaderRoute: typeof ConsoleCompaniesNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/library/': {
      id: '/console/library/'
      path: '/library'
      fullPath: '/console/library/'
      preLoaderRoute: typeof ConsoleLibraryIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/resumes/': {
      id: '/console/resumes/'
      path: '/resumes'
      fullPath: '/console/resumes/'
      preLoaderRoute: typeof ConsoleResumesIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/resumes/$resumeId': {
      id: '/console/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/console/resumes/$resumeId'
      preLoaderRoute: typeof ConsoleResumesResumeIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/resumes/new': {
      id: '/console/resumes/new'
      path: '/resumes/new'
      fullPath: '/console/resumes/new'
      preLoaderRoute: typeof ConsoleResumesNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/resumes/$resumeId/polish': {
      id: '/console/resumes/$resumeId/polish'
      path: '/polish'
      fullPath: '/console/resumes/$resumeId/polish'
      preLoaderRoute: typeof ConsoleResumesResumeIdPolishRouteImport
      parentRoute: typeof ConsoleResumesResumeIdRoute
    }
    '/console/resumes/$resumeId/targets': {
      id: '/console/resumes/$resumeId/targets'
      path: '/targets'
      fullPath: '/console/resumes/$resumeId/targets'
      preLoaderRoute: typeof ConsoleResumesResumeIdTargetsRouteImport
      parentRoute: typeof ConsoleResumesResumeIdRoute
    }
  }
}

interface ConsoleResumesResumeIdRouteChildren {
  ConsoleResumesResumeIdPolishRoute: typeof ConsoleResumesResumeIdPolishRoute
  ConsoleResumesResumeIdTargetsRoute: typeof ConsoleResumesResumeIdTargetsRoute
}

const ConsoleResumesResumeIdRouteChildren: ConsoleResumesResumeIdRouteChildren =
  {
    ConsoleResumesResumeIdPolishRoute: ConsoleResumesResumeIdPolishRoute,
    ConsoleResumesResumeIdTargetsRoute: ConsoleResumesResumeIdTargetsRoute,
  }

const ConsoleResumesResumeIdRouteWithChildren =
  ConsoleResumesResumeIdRoute._addFileChildren(
    ConsoleResumesResumeIdRouteChildren,
  )

interface ConsoleRouteRouteChildren {
  ConsoleAdvisorRoute: typeof ConsoleAdvisorRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleCompaniesCompanyIdRoute: typeof ConsoleCompaniesCompanyIdRoute
  ConsoleCompaniesNewRoute: typeof ConsoleCompaniesNewRoute
  ConsoleResumesResumeIdRoute: typeof ConsoleResumesResumeIdRouteWithChildren
  ConsoleResumesNewRoute: typeof ConsoleResumesNewRoute
  ConsoleCompaniesIndexRoute: typeof ConsoleCompaniesIndexRoute
  ConsoleLibraryIndexRoute: typeof ConsoleLibraryIndexRoute
  ConsoleResumesIndexRoute: typeof ConsoleResumesIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAdvisorRoute: ConsoleAdvisorRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleCompaniesCompanyIdRoute: ConsoleCompaniesCompanyIdRoute,
  ConsoleCompaniesNewRoute: ConsoleCompaniesNewRoute,
  ConsoleResumesResumeIdRoute: ConsoleResumesResumeIdRouteWithChildren,
  ConsoleResumesNewRoute: ConsoleResumesNewRoute,
  ConsoleCompaniesIndexRoute: ConsoleCompaniesIndexRoute,
  ConsoleLibraryIndexRoute: ConsoleLibraryIndexRoute,
  ConsoleResumesIndexRoute: ConsoleResumesIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  ApiAdvisorRoute: ApiAdvisorRoute,
  ApiPolishRoute: ApiPolishRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJdIngestRoute: ApiJdIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
