/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiAdvisorRouteImport } from './routes/api/advisor'
import { Route as ApiFetchJobsRouteImport } from './routes/api/fetch-jobs'
import { Route as ApiPolishRouteImport } from './routes/api/polish'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'
import { Route as CompaniesNewRouteImport } from './routes/companies/new'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes/index'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes/$resumeId'
import { Route as ResumesNewRouteImport } from './routes/resumes/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ResumesResumeIdPolishRouteImport } from './routes/resumes/$resumeId.polish'
import { Route as ResumesResumeIdTargetsRouteImport } from './routes/resumes/$resumeId.targets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchJobsRoute = ApiFetchJobsRouteImport.update({
  id: '/api/fetch-jobs',
  path: '/api/fetch-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishRoute = ApiPolishRouteImport.update({
  id: '/api/polish',
  path: '/api/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesNewRoute = ResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdPolishRoute = ResumesResumeIdPolishRouteImport.update({
  id: '/polish',
  path: '/polish',
  getParentRoute: () => ResumesResumeIdRoute,
} as any)
const ResumesResumeIdTargetsRoute = ResumesResumeIdTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => ResumesResumeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/fetch-jobs': typeof ApiFetchJobsRoute
  '/api/polish': typeof ApiPolishRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRouteWithChildren
  '/resumes/new': typeof ResumesNewRoute
  '/companies/': typeof CompaniesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resumes/$resumeId/polish': typeof ResumesResumeIdPolishRoute
  '/resumes/$resumeId/targets': typeof ResumesResumeIdTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/fetch-jobs': typeof ApiFetchJobsRoute
  '/api/polish': typeof ApiPolishRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRouteWithChildren
  '/resumes/new': typeof ResumesNewRoute
  '/companies': typeof CompaniesIndexRoute
  '/library': typeof LibraryIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resumes/$resumeId/polish': typeof ResumesResumeIdPolishRoute
  '/resumes/$resumeId/targets': typeof ResumesResumeIdTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/fetch-jobs': typeof ApiFetchJobsRoute
  '/api/polish': typeof ApiPolishRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRouteWithChildren
  '/resumes/new': typeof ResumesNewRoute
  '/companies/': typeof CompaniesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resumes/$resumeId/polish': typeof ResumesResumeIdPolishRoute
  '/resumes/$resumeId/targets': typeof ResumesResumeIdTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisor'
    | '/login'
    | '/mcp'
    | '/api/advisor'
    | '/api/fetch-jobs'
    | '/api/polish'
    | '/companies/$companyId'
    | '/companies/new'
    | '/resumes/$resumeId'
    | '/resumes/new'
    | '/companies/'
    | '/library/'
    | '/resumes/'
    | '/api/auth/$'
    | '/resumes/$resumeId/polish'
    | '/resumes/$resumeId/targets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisor'
    | '/login'
    | '/mcp'
    | '/api/advisor'
    | '/api/fetch-jobs'
    | '/api/polish'
    | '/companies/$companyId'
    | '/companies/new'
    | '/resumes/$resumeId'
    | '/resumes/new'
    | '/companies'
    | '/library'
    | '/resumes'
    | '/api/auth/$'
    | '/resumes/$resumeId/polish'
    | '/resumes/$resumeId/targets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisor'
    | '/login'
    | '/mcp'
    | '/api/advisor'
    | '/api/fetch-jobs'
    | '/api/polish'
    | '/companies/$companyId'
    | '/companies/new'
    | '/resumes/$resumeId'
    | '/resumes/new'
    | '/companies/'
    | '/library/'
    | '/resumes/'
    | '/api/auth/$'
    | '/resumes/$resumeId/polish'
    | '/resumes/$resumeId/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisorRoute: typeof AdvisorRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ApiAdvisorRoute: typeof ApiAdvisorRoute
  ApiFetchJobsRoute: typeof ApiFetchJobsRoute
  ApiPolishRoute: typeof ApiPolishRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRouteWithChildren
  ResumesNewRoute: typeof ResumesNewRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-jobs': {
      id: '/api/fetch-jobs'
      path: '/api/fetch-jobs'
      fullPath: '/api/fetch-jobs'
      preLoaderRoute: typeof ApiFetchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish': {
      id: '/api/polish'
      path: '/api/polish'
      fullPath: '/api/polish'
      preLoaderRoute: typeof ApiPolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/new': {
      id: '/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof ResumesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId/polish': {
      id: '/resumes/$resumeId/polish'
      path: '/polish'
      fullPath: '/resumes/$resumeId/polish'
      preLoaderRoute: typeof ResumesResumeIdPolishRouteImport
      parentRoute: typeof ResumesResumeIdRoute
    }
    '/resumes/$resumeId/targets': {
      id: '/resumes/$resumeId/targets'
      path: '/targets'
      fullPath: '/resumes/$resumeId/targets'
      preLoaderRoute: typeof ResumesResumeIdTargetsRouteImport
      parentRoute: typeof ResumesResumeIdRoute
    }
  }
}

interface ResumesResumeIdRouteChildren {
  ResumesResumeIdPolishRoute: typeof ResumesResumeIdPolishRoute
  ResumesResumeIdTargetsRoute: typeof ResumesResumeIdTargetsRoute
}

const ResumesResumeIdRouteChildren: ResumesResumeIdRouteChildren = {
  ResumesResumeIdPolishRoute: ResumesResumeIdPolishRoute,
  ResumesResumeIdTargetsRoute: ResumesResumeIdTargetsRoute,
}

const ResumesResumeIdRouteWithChildren = ResumesResumeIdRoute._addFileChildren(
  ResumesResumeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisorRoute: AdvisorRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ApiAdvisorRoute: ApiAdvisorRoute,
  ApiFetchJobsRoute: ApiFetchJobsRoute,
  ApiPolishRoute: ApiPolishRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  ResumesResumeIdRoute: ResumesResumeIdRouteWithChildren,
  ResumesNewRoute: ResumesNewRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
